query ListPublicPosts @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  posts(where: { isPublic: { eq: true } }) {
    id
    title
    content
    createdAt
  }
}

mutation CreatePost($title: String!, $content: String!, $isPublic: Boolean!) @auth(level: USER) {
  post_insert(data: {
    title: $title
    content: $content
    isPublic: $isPublic
    authorUid_expr: "auth.uid"
    createdAt_expr: "request.time"
  })
}

mutation UpdatePost($id: UUID!, $title: String, $content: String, $isPublic: Boolean) @auth(level: USER) {
  post_update(key: { id: $id }, data: {
    title: $title
    content: $content
    isPublic: $isPublic
    updatedAt_expr: "request.time"
  })
}

mutation DeletePost($id: UUID!) @auth(level: USER) {
  post_delete(key: { id: $id })
}